name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --onefile --icon=icon.ico --add-data "gs;gs" --add-data "GSPRINT;GSPRINT" main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: printPDF-exe
        path: dist/*.exe
